version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true=value
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
    command: "yarn start"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=database;Database=TaskManager;UID=sa;Password=password@123456#

  database:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "password@123456#"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - ./database/data/:/var/opt/mssql/data
    ports:
      - "1433:1433"
